services:
  postgres:
    image: postgres:14
    container_name: tournament_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tournament
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tournament-network

  auth-database:
    image: postgres:14
    container_name: auth_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: authentication
    ports:
      - "5433:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data
    networks:
      - tournament-network

#  api:
#    build:
#      context: ../backend
#      dockerfile: Dockerfile
#    container_name: tournament_api
#    restart: always
#    depends_on:
#      - postgres
#    environment:
#      USE_POSTGRES: "true"
#      DB_HOST: postgres
#      DB_PORT: 5432
#      DB_USER: postgres
#      DB_PASSWORD: postgres
#      DB_NAME: tournament
#      DB_SSLMODE: disable
#    ports:
#      - "3000:3000"
#    networks:
#      - tournament-network

networks:
  tournament-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  auth_data:
    driver: local