services:
  engine-database:
    image: postgres:18
    container_name: tournament_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tournament
    ports:
      - "5432:5432"
    volumes:
      - engine_data:/var/lib/postgresql
    networks:
      - tournament-network

  identity-service-database:
    image: postgres:18
    container_name: identity_service_postgres
    restart: always
    env_file:
      - ./.identity-service.env
    ports:
      - "5433:5432"
    volumes:
      - identity_data:/var/lib/postgresql
    networks:
      - tournament-network

networks:
  tournament-network:
    driver: bridge

volumes:
  engine_data:
    driver: local
  identity_data:
    driver: local