[package]
name = "authentication"
version = "0.1.0"
edition = "2021"

[dependencies]
jsonwebtoken = "9.3.1"
tonic = "0.12.3"
prost = "0.13.5"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }

[build-dependencies]
tonic-build = "0.12.3"